services:
  mongo-db:
    image: mongo:6.0
    container_name: payment_mongo_local
    restart: always
    ports:
      - "${MONGO_PORT}:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${DB_NAME}
    volumes:
      - mongo_data:/data/db

  mongo-express:
    image: mongo-express
    container_name: payment_mongo_ui
    restart: always
    ports:
      - "${MONGO_UI_PORT}:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${ADMINUSERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${ADMINPASSWORD}
      ME_CONFIG_MONGODB_URL: ${MONGODB_URL}
      ME_CONFIG_BASICAUTH_USERNAME: ${BASICAUTH_USERNAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${BASICAUTH_PASSWORD}
    depends_on:
      - mongo-db

volumes:
  mongo_data:
