spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://authservice-app:${AUTH_APP_PORT}/api/auth/.well-known/jwks.json

management.metrics.tags.application=${spring.application.name}
management.tracing.sampling.probability=1.0
management.otlp.tracing.endpoint=http://tempo:4318/v1/traces
logging.pattern.level=%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]