spring.application.name=payment-service

server.port=${APP_PORT}

data.mongodb.uri=${MONGO_URI}
data.mongodb.auto-index-creation=false

liquidbase.enabled=true
liquidbase.change-log=classpath:db/changelog/db.changelog-master.json
