spring.application.name=payment-service

server.port=${APP_PORT}

spring.data.mongodb.uri=${MONGO_URI}
spring.data.mongodb.database=payment_db
spring.data.mongodb.auto-index-creation=false

spring.liquibase.enabled=true
spring.liquibase.change-log=db/changelog/db.changelog-master.json